apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: krishnakrmahto97/sampleprojects-currencyexchangeservice:0.0.13-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: sampleprojects-currencyexchangeservice
      restartPolicy: Always
