version: '3.7'

services:
  currency-exchnage:
    image: krishnakrmahto97/sampleprojects/currencyexchangeservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-discovery:8761/eureka
      - spring.zipkin.baseUrl=http://zipkin-server:9411

  currency-conversion:
    image: krishnakrmahto97/sampleprojects/currencyconversionservice:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-discovery:8761/eureka
      - spring.zipkin.baseUrl=http://zipkin-server:9411

  api-gateway:
    image: krishnakrmahto97/sampleprojects/springcloudapigateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-discovery:8761/eureka
      - spring.zipkin.baseUrl=http://zipkin-server:9411

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - eureka-discovery

  eureka-discovery:
    image: krishnakrmahto97/sampleprojects/eurekadiscoveryserver:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: